package com.lastcalleats.auth.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Date;

/**
 * This utility class is responsible for generating, parsing, and validating JWT tokens.
 * It centralizes all token-related operations so that authentication logic remains consistent
 * across the application.
 *
 * The token generated by this class contains the user ID and role, which are later used
 * for authentication and authorization in protected requests.
 */
@Component
public class JwtUtil {

  @Value("${app.jwt.secret}")
  private String secret;

  @Value("${app.jwt.expiration-ms:86400000}")
  private long expirationMs;

  private SecretKey secretKey;

  /**
   * Initializes the secret key after the configuration values are loaded.
   *
   * This method converts the configured secret string into a SecretKey object
   * that can be used for signing and validating JWT tokens.
   */
  @PostConstruct
  public void init() {
    this.secretKey = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
  }

  /**
   * Generates a signed JWT token for a specific account.
   *
   * The generated token contains the user ID as the subject and stores the role
   * as a custom claim. It also includes issued time and expiration time.
   *
   * @param userId the unique ID of the authenticated user or merchant
   * @param role the role of the authenticated account
   * @return a signed JWT token string
   */
  public String generateToken(Long userId, String role) {
    Date now = new Date();
    Date expireDate = new Date(now.getTime() + expirationMs);

    return Jwts.builder()
        .subject(String.valueOf(userId))
        .claim("role", role)
        .issuedAt(now)
        .expiration(expireDate)
        .signWith(secretKey)
        .compact();
  }

  /**
   * Extracts the user ID from a JWT token.
   *
   * The user ID is stored as the token subject and is converted back to a Long
   * so it can be used by the application.
   *
   * @param token the JWT token
   * @return the user ID stored in the token
   */
  public Long extractUserId(String token) {
    Claims claims = extractAllClaims(token);
    return Long.valueOf(claims.getSubject());
  }

  /**
   * Extracts the role claim from a JWT token.
   *
   * This role is later used by Spring Security to determine what the current
   * authenticated account is allowed to access.
   *
   * @param token the JWT token
   * @return the role stored in the token
   */
  public String extractRole(String token) {
    Claims claims = extractAllClaims(token);
    return claims.get("role", String.class);
  }

  /**
   * Validates whether a JWT token is still usable.
   *
   * A token is considered valid if it can be parsed successfully and its expiration
   * time is still later than the current system time.
   *
   * @param token the JWT token
   * @return true if the token is valid and not expired, otherwise false
   */
  public boolean validateToken(String token) {
    try {
      Claims claims = extractAllClaims(token);
      return claims.getExpiration().after(new Date());
    } catch (Exception e) {
      return false;
    }
  }

  /**
   * Parses all claims from a JWT token.
   *
   * This internal helper method is used by other public methods to avoid duplicating
   * token parsing logic in multiple places.
   *
   * @param token the JWT token
   * @return all claims contained in the token
   */
  public Claims extractAllClaims(String token) {
    return Jwts.parser()
        .verifyWith(secretKey)
        .build()
        .parseSignedClaims(token)
        .getPayload();
  }
}